export enum ActionType {
    REGISTER_LOADING = "REGISTER_LOADING",
    REGISTER_ERROR = "REGISTER_ERROR",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",

    LOGIN_LOADING = "LOGIN_LOADING",
    LOGIN_ERROR = "LOGIN_ERROR",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    
    LOGOUT_LOADING = "LOGOUT_LOADING",
    LOGOUT_ERROR = "LOGOUT_ERROR",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

    VERIFY_EMAIL_LOADING = "VERIFY_EMAIL_LOADING",
    VERIFY_EMAIL_ERROR = "VERIFY_EMAIL_ERROR",
    VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS",

    ME_LOADING = "ME_LOADING",
    ME_SUCCESS = "ME_SUCCESS",
    ME_ERROR = "ME_ERROR",

    USER_UPDATE_LOADING = "USER_UPDATE_LOADING",
    USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
    USER_UPDATE_ERROR = "USER_UPDATE_ERROR",

    PASSWORD_UPDATE_LOADING = "PASSWORD_UPDATE_LOADING",
    PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS",
    PASSWORD_UPDATE_ERROR = "PASSWORD_UPDATE_ERROR",

    AVATAR_UPDATE_LOADING = "AVATAR_UPDATE_LOADING",
    AVATAR_UPDATE_SUCCESS = "AVATAR_UPDATE_SUCCESS",
    AVATAR_UPDATE_ERROR = "AVATAR_UPDATE_ERROR",

}

export enum ClearTypes {
    CLEAR_AUTH = "CLEAR_AUTH",
    CLEAR_ME = "CLEAR_ME",
}